version: '3.7'
services:
    prodigy:
        image: thaddeuskkr/prodigy
        build: .
        container_name: prodigy
        restart: on-failure
        tty: true
        environment: 
            - token=notyet